### ISSUE TITLE
Remove dependency on github.com/dgryski/go-metro

### ISSUE THREAD

**Issue by tamird** [axiomhq/hyperloglog#12]
github.com/dgryski/go-metro is written largely in gc-syntax assembly, which makes it difficult to support gccgo downstream of it.

cc @dgryski

**Comment by dgryski** [comment]
Sadly I think you'll find most high-speed hash functions will have assembly cores.  The question is can we produce assembly code that's suitable for gccgo too ?  I'd certainly be up for investigating that approach.

**Comment by dgryski** [comment]
Note that go-metro does have a pure-Go implementation as well.  That should be sufficient for your purposes.

**Comment by tamird** [comment]
Yup, I've been building with that build tag. Still, if something more portable (e.g. [`hash/fnv`](https://godoc.org/hash/fnv)) is sufficiently fast, it would be nice to avoid the hoop-jumping.

**Comment by dgryski** [comment]
My guess is that `go-metro` is faster than `hash/fnv` even without the `go-metro` assembly core.

**Comment by seiflotfy** [comment]
what changes are required from my side for this?

**Comment by tamird** [comment]
If you don't want to use a different algorithm, you'd have to use something
like github.com/shivakar/metrohash instead of go-metro. Unfortunately,
go-metro is non-portable by default (and opting-in to portable code
requires build tags, which must be specified downstream).

**Comment by seiflotfy** [comment]
@dgryski can you also run github.com/shivakar/metrohash ?

**Comment by dgryski** [comment]
```
BenchmarkShivMetro/1-8 	30000000	        43.8 ns/op	  22.84 MB/s
BenchmarkShivMetro/2-8 	30000000	        45.2 ns/op	  44.23 MB/s
BenchmarkShivMetro/3-8 	30000000	        44.4 ns/op	  67.61 MB/s
BenchmarkShivMetro/4-8 	30000000	        42.1 ns/op	  95.03 MB/s
BenchmarkShivMetro/5-8 	30000000	        47.1 ns/op	 106.06 MB/s
BenchmarkShivMetro/10-8         	30000000	        46.8 ns/op	 213.60 MB/s
BenchmarkShivMetro/20-8         	30000000	        49.9 ns/op	 400.77 MB/s
BenchmarkShivMetro/30-8         	30000000	        56.9 ns/op	 527.32 MB/s
BenchmarkShivMetro/40-8         	20000000	        51.0 ns/op	 784.21 MB/s
BenchmarkShivMetro/50-8         	30000000	        58.7 ns/op	 852.36 MB/s
BenchmarkShivMetro/60-8         	20000000	        57.9 ns/op	1035.74 MB/s
BenchmarkShivMetro/70-8         	20000000	        60.4 ns/op	1158.89 MB/s
BenchmarkShivMetro/80-8         	20000000	        57.8 ns/op	1385.27 MB/s
BenchmarkShivMetro/90-8         	20000000	        62.5 ns/op	1441.11 MB/s
BenchmarkShivMetro/100-8        	20000000	        63.9 ns/op	1565.38 MB/s
BenchmarkShivMetro/1024-8       	10000000	       156 ns/op	6558.53 MB/s
BenchmarkShivMetro/8192-8       	 2000000	       881 ns/op	9294.99 MB/s
```

I don't understand the performance for the last two entries (1024, 8192 bytes) given that it seems so much slower the rest of the time.

**Comment by seiflotfy** [comment]
@dgryski is it an option if you created a repo with the pure go implementation that I can use?

**Comment by dgryski** [comment]
Adding `gccgo` build tags for `go-metro` is probably easier.

**Comment by dgryski** [comment]
I've added gccgo build tags *and* sped up the go-metro inner loop.

**Comment by dgryski** [comment]
This can be closed.
