### ISSUE TITLE
Explicit public toNormal method

### ISSUE THREAD

**Issue by fastest963** [axiomhq/hyperloglog#13]
We have thousands of distinct datasets that we merge together and the underlying Sketch's get Merge called to get a resulting Sketch. We're seeing a significant amount of time spent in `maybeToNormal`.
![image](https://user-images.githubusercontent.com/112555/48422094-e700cf00-e72b-11e8-8259-207c91423abf.png)

Would it be better for us to store all of the datasets with the "normal" Sketch instead of a sparse one? In other words, we'd call `ToNormal` (or something like that) before calling `MarshalBinary`. Would this reduce the time spent merging?

**Comment by seiflotfy** [comment]
First of all thanks so much for taking the time to plot this... this is great
1) so Sparse improves the estimation of low cardinalities...
2) once somethign is normalized it can't be switched back
3) what about adding a NewNoSparse function that creates a HyperLogLog sketch without sparse?

**Comment by fastest963** [comment]
That works as well. Would you recommend that we always call NewNoSparse since our data sizes are always greater than 100? Finally, since we're calling MarshalBinary to store the data and then fetching it later using UnmarshalBinary, how could we have UnmarshalBinary not call New and call NewNoSparse? Is there a way we can signal to UnmarshalBinary that we've already called New and it's initialized with the right precision?
