### ISSUE TITLE
request: insert-hash method

### ISSUE THREAD

**Issue by RaduBerinde** [axiomhq/hyperloglog#6]
It would be useful to have an insert method that just takes the hash value directly. This would allow the caller to choose the hash function. It is particularly useful if our data is just integers - we could use some function that works on integers directly instead of converting them to `[]byte`.

**Comment by seiflotfy** [comment]
On it

**Comment by seiflotfy** [comment]
Thanks @dvillega 
@RaduBerinde what do you think?

**Comment by RaduBerinde** [comment]
Nice, thanks!

**Comment by seiflotfy** [comment]
@RaduBerinde if its too slow you might want to try github.com/seiflotfy/loglogbeta
It should be faster since it uses 1 byte registers no never needs to shift and doesn't use sparse
